# Generated by Django 5.0.1 on 2024-09-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cooking_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='SmartKitchen_App.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('recipes', models.ManyToManyField(to='SmartKitchen_App.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartKitchen_App.user')),
            ],
        ),
    ]
