# Generated by Django 5.0.1 on 2024-10-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
