# Generated by Django 5.0.1 on 2024-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SmartKitchen_App', '0003_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('ingridents', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('prep_time', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
            ],
        ),
    ]
