# Generated by Django 4.2.7 on 2024-10-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
