# Generated by Django 4.2.7 on 2024-10-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0010_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
