# Generated by Django 4.2.7 on 2024-10-14 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0011_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('ingridents', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('prep_time', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
