# Generated by Django 4.2.7 on 2024-11-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0012_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
