# Generated by Django 4.2.7 on 2024-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0013_delete_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthAnalysis',
        ),
    ]
