# Generated by Django 5.1.3 on 2024-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartKitchen_App', '0017_healthanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthanalysis',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
